@echo off
del "os_image.bin" 2>NUL 1>NUL
echo building boot...
nasm -felf32 boot.asm -o boot.o
echo building kernel...
i686-elf-gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building common...
i686-elf-gcc -c include/common.c -o common.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building vga...
i686-elf-gcc -c include/vga.c -o vga.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building error...
i686-elf-gcc -c include/error.c -o error.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building screencontroller...
i686-elf-gcc -c include/screencontroller.c -o screencontroller.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building gdt...
i686-elf-gcc -c include/gdt.c -o gdt.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building idt...
i686-elf-gcc -c include/idt.c -o idt.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building isr...
i686-elf-gcc -c include/isr.c -o isr.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building irq...
i686-elf-gcc -c include/irq.c -o irq.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building kbd...
i686-elf-gcc -c include/kbd.c -o kbd.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building timer...
i686-elf-gcc -c include/timer.c -o timer.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building shell...
i686-elf-gcc -c include/shell.c -o shell.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo building fat...
i686-elf-gcc -c include/fat.c -o fat.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Wno-unused-parameter
echo linking...
i686-elf-gcc -T linker.ld -o os_image.bin -ffreestanding -O2 -nostdlib boot.o kernel.o fat.o shell.o kbd.o timer.o irq.o isr.o idt.o gdt.o error.o vga.o common.o screencontroller.o -lgcc -std=gnu99 -Wno-unused-parameter
copy os_image.bin boot 2>NUL 1>NUL
cd boot 2>NUL 1>NUL
del CodeOSKernel 2>NUL 1>NUL
rename "os_image.bin" "CodeOSKernel" 2>NUL 1>NUL
cd .. 2>NUL 1>NUL
if exist "os_image.bin" (
	COLOR 02
	echo BUILD SUCCEEDED
) else (
    COLOR 0C
	echo BUILD FAILED
)
del *.o 2>NUL 1>NUL
PAUSE